version: "3.9"

services:

  api:
    build:
      context: ./clinical-mdr-api
      dockerfile: Dockerfile
      args:
        TARGET: prod
    environment:
      NEO4J_DSN: "${NEO4J_DSN}"
      ALLOW_ORIGIN_REGEX: ".*"
      OAUTH_ENABLED: "false"
      OAUTH_RBAC_ENABLED: "false"
      UVICORN_PORT: 5003
      UVICORN_ROOT_PATH: "/api"
    expose:
      - "8501:5003"

  consumerapi:
    build:
      context: ./clinical-mdr-api
      dockerfile: Dockerfile
      args:
        TARGET: prod
    environment:
      NEO4J_DSN: "${NEO4J_DSN}"
      ALLOW_ORIGIN_REGEX: ".*"
      OAUTH_ENABLED: "false"
      OAUTH_RBAC_ENABLED: "false"
      UVICORN_PORT: 5008
      UVICORN_ROOT_PATH: "/consumer-api"
      UVICORN_APP: consumer_api.consumer_api:app
    expose:
      - "8502:5008"

  frontend:
    build:
      context: ./studybuilder
      dockerfile: Dockerfile
      args:
        NGINX_IMAGE: nginx:alpine
        NODE_IMAGE: node:lts-alpine
    environment:
      API_BASE_URL: ""
      DOC_BASE_URL: "/doc"
      NEODASH_BASE_URL: "/neodash"
      OAUTH_ENABLED: "false"
    ports:
      - "8505:5005"
    depends_on:
      api:
        condition: service_started
      documentation:
        condition: service_started
      neodash:
        condition: service_started

  documentation:
    build:
      context: ./documentation-portal
      dockerfile: Dockerfile

  neodash:
    build:
      context: ./osb-neodash
      dockerfile: Dockerfile
      args:
        NODE_IMAGE: node:lts-alpine
        NGINX_IMAGE: nginx:alpine
    environment:
      NGINX_PORT: 5007
      ssoEnabled: "false"
      standalone: "true"
      standaloneProtocol: "neo4j"
      standaloneHost: "10.161.18.181"
      standalonePort: "7687"
      standaloneDatabase: "openstudybuilder"
      standaloneAllowLoad: "true"
      standaloneDashboardName: "Activity Library Dashboard"
      standaloneDashboardDatabase: "openstudybuilder"
      standaloneUsername: "neo4j"
      standalonePassword: "${NEO4J_PASSWORD}"
    ports:
      - "8507:5007"
